### ISSUE TITLE
Use `/sw.js_data` to extract config data

### ISSUE THREAD

**Issue by LuanRT** [VueTubeApp/VueTube-Extractor#2]
### Describe your suggested feature

Hi there,

It seems like the service worker endpoint ([`sw.js`](https://www.youtube.com/sw.js)) will sometimes fail to return the config data (depending on where/when the extractor is running). 

This can be fixed by using [`/sw.js_data`](https://www.youtube.com/sw.js_data) instead, which doesn't return any js/html, and is likely what provides data to [`sw.js`](https://www.youtube.com/sw.js).

### Other details

See [this issue](https://github.com/LuanRT/YouTube.js/issues/55) for more context.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by 404-Program-not-found** [comment]
thank you for the heads up! much appreciated 🙂

**Comment by 404-Program-not-found** [comment]
this has now been implemented in cb16696 and will be closed now.
